### ISSUE TITLE
Period of Black Before Video Begins

### ISSUE THREAD

**Issue by asethwright** [amzn/web-app-starter-kit-for-fire-tv#25]
I am loading an MP4 video into the player from a remote host. There is a period of black before the video begins to play. Is this a limitation of the device due to rendering? I don't get this black (maybe 2 seconds) on my Mac, only when testing on the actual FireTV stick.

Any help would be appreciated.

**Comment by craigcbrunner-amazon** [comment]
This is due to the FireTV stick processing time to load the video, we have actually helped alleviate this issue on an upcoming release by showing the spinner for a longer period until the video is actually ready to play(we are using the canplay event in your current code, but that event is firing too early). I am not sure when this code will hit mainline.

**Comment by asethwright** [comment]
No worries! Thanks for the response.

**Comment by jfrux** [comment]
any updates on this?
