### ISSUE TITLE
web app simple live video error 

### ISSUE THREAD

**Issue by trburns** [amzn/web-app-starter-kit-for-fire-tv#36]
when i test my web app in the app tester on the fire stick im getting a video error on the live stream it will play for a second and them the error will appear

**Comment by CrandellWS** [comment]
There is an issue sometimes with CORS ... I am thinking this is your issue as I have seen it as the most common can't get it to run problem...

Usually, one can tell by disabling it all together and if it works then most likely it is a CORS issue...

Personally, I use a chrome extension that I can turn on and off while developing... 


https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog


If this does not help can you give more description on the error or copy and paste a **_small_** portion of it that might show insight...

**Comment by CrandellWS** [comment]
This issue should be combined with #35 see 

https://github.com/amzn/web-app-starter-kit-for-fire-tv/issues/35#issuecomment-268331714

**Comment by maryga-amazon** [comment]
If you are using an API that has not given access to your hosted app domain then you can use the packaged app solution. This is because the packaged app includes the web app components and it is served from the local filesystem, this will solve the CORS issues.
Using a zip package for your web app will allow your app to work on Fire TV (for both testing in WAT & submitting to appstore).
