### ISSUE TITLE
MRSS with video from Vimeo or other CDN?

### ISSUE THREAD

**Issue by flamablecharlie** [amzn/web-app-starter-kit-for-fire-tv#57]
So I'm working with the MRSS sample. The provided genericMediaData.xml works as expected. 

But when substituting my own URLs on Vimeo, I get "Video Feed Error An unexpected error occurred. Select OK to exit, or try again."

So I tried with a preformatted MRSS from Vimeo. Same result.

I know there is a sample for Youtube video, but what about those of us with Vimeo, or other CDNs? Is there a workaround, or are we just stuck?

It would be cost prohibitive to mirror our videos to Cloudfront, and a major pain to change over to another CDN, as well as breaking our established channel outlets on other platforms.

**Comment by russellbeattie-amazon** [comment]
Is the problem in the access to the MRSS feed (a CORS problem) or is it a problem playing the videos.

The solution to the feed issue is to use a proxy to the feed's server so you can add into the proper CORS permissions to the response headers. The solution to the playback may be to use Vimeo's player instead of the plain MP4 player. (Obviously YouTube's player won't work as it's tied to their content). 

Does that help?

**Comment by flamablecharlie** [comment]
As far as I can tell, the feed access is just fine. I threw together a web script to play it, and it plays with no errors. But the firetv script errors every time. If I load up the MRSS with the sample data from Amazon, it works fine on both players. So the problem is with firetv's player.

How would I incorporate Vimeo's player into the firetv player script? Sorry if that sounds like a stupid question, but I'm brand new to programming a firetv app.

**Comment by russellbeattie-amazon** [comment]
The bottom-line answer is that the project doesn't support Vimeo out-of-the-box. You'll have to do the development to swap out the MP4/YouTube player code for Vimeo player code. It's non-trivial, so if you're not a web developer, you may want to look for another solution.

**Comment by flamablecharlie** [comment]
I see... So I'll start looking for another route. Thanks!

**Comment by wilsharo** [comment]
@flamablecharlie I was getting a similar error to you. With an additional message saying video format is not supported. The issue was due to the video link I was using. I was able to resolve this by logging into my Vimeo Pro account. Then selecting a video in order to access it's settings. Then select Distribution >> video file links. Under the section that states "Anyone with access to these links will be able to view and download your video." click the drop down button and select "Download the video". Then any of the video links available will play successfully. Add them to your  genericMediaData file or wherever you are using as a media feed. I attached a screenshot to help you understand the steps. Hope this helps you and others. Regards
![Screenshot 2019-03-09 at 19 08 15](https://user-images.githubusercontent.com/26722718/54075460-d3abdd80-429f-11e9-887d-bc9f88473308.png)
