### ISSUE TITLE
Livestream-Example not working in Chrome or Web App Tester

### ISSUE THREAD

**Issue by pc-coholic** [amzn/web-app-starter-kit-for-fire-tv#8]
Hi!

I tried running the [live media example](https://amzn.github.io/web-app-starter-kit-for-fire-tv/simple-live/) directly on chrome (Version 43.0.2357.52 beta (64-bit)) and also on a non-fire-tablet using the Web App Tester.

The result is always the same: The live-video is not loaded - just an infinite spinner...

Is this a problem with your demo-code? Or is this just because I am not using a fire-device (I don't have one on hand - yet)...

**Comment by craigcbrunner-amazon** [comment]
Hey, 
The live stream example uses HLS video. Many browsers HTML5 players do not support HLS video, including desktop chrome. The WebView FireTV and FireTV stick supports HLS through the the HTML5 video player, which is why the example works on FireTV/Stick. I am not sure about other device support for HLS, since the Starter Kit is designed for FireTV/FireTV Stick, however I believe some Fire Tablets support HLS through the HTML5 video player as well. I do know for sure that Chrome on desktop does not support it.

Please let me know if there is anything else I can answer. On desktop you can take the stream URL(it is a public NASA stream) and play it though some desktop media players such as VLC. 

So to quickly answer your question, the demo code should be working you just need a device with a WebView or browser that supports HLS, such as the FireTV.

Thanks!
-Craig

**Comment by pc-coholic** [comment]
Thanks for the information, Craig! One more reason to look forward to the delivery of my FireTV-Stick ;-)
